name: buf
on:
  push:
  delete:
permissions:
  contents: read
jobs:
  # Name of module should correspond to the quickstart
  bsr-module:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - uses: bufbuild/buf-action@v1
        with:
          input: bsr/start/server/proto
          token: ${{ secrets.BUF_TOKEN }}
